[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.devnet]
feed = "orcdW2S1VR5kt8axERS4cJuiywxLPKo3qYYqN3Di5s4"
guard = "grddH13wp77vjwV2WwzbVXAkgRGQuTHkj1hKcECtHRt"
irm = "irmdacogiedKeCEBh72FJx4aoixyaByqGikTkxGifUk"
jbl = "c1md3yLhwBxREDRc2HcX4ivTigoyJ3No3DehkzjaPT8"

[programs.localnet]
feed = "orcdW2S1VR5kt8axERS4cJuiywxLPKo3qYYqN3Di5s4"
guard = "grddH13wp77vjwV2WwzbVXAkgRGQuTHkj1hKcECtHRt"
irm = "irmdacogiedKeCEBh72FJx4aoixyaByqGikTkxGifUk"
jbl = "c1md3yLhwBxREDRc2HcX4ivTigoyJ3No3DehkzjaPT8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"

[hooks]
